using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using PlayniteApiServer.Controllers;

namespace PlayniteApiServer.Server.OpenApi
{
    /// <summary>
    /// Hand-authored OpenAPI 3.0.3 component schemas. Each method returns a
    /// JObject fragment that the <see cref="OpenApiBuilder"/> drops into the
    /// document's <c>components.schemas</c> section.
    ///
    /// The Game schema is generated by walking
    /// <see cref="GamesController.AllowedPatchFields"/> — the same source of
    /// truth used by the patch validator. The result is that the spec's
    /// "writable" surface literally cannot drift from the validator. The one
    /// exception is <c>releaseDate</c>, which is a nested struct in the
    /// SDK and is rendered explicitly here.
    /// </summary>
    internal static class OpenApiSchemas
    {
        /// <summary>
        /// Constants for $ref strings. Use these from RouteBuilder calls
        /// instead of magic strings.
        /// </summary>
        public static class Schemas
        {
            public const string Error           = "#/components/schemas/Error";
            public const string Game            = "#/components/schemas/Game";
            public const string GameCreate      = "#/components/schemas/GameCreate";
            public const string GamePage        = "#/components/schemas/GamePage";
            public const string NamedItem       = "#/components/schemas/NamedItem";
            public const string NamedItemCreate = "#/components/schemas/NamedItemCreate";
            public const string Platform        = "#/components/schemas/Platform";
        }

        public static JObject BuildAll()
        {
            return new JObject
            {
                ["Error"]           = Error(),
                ["Game"]            = Game(),
                ["GameCreate"]      = GameCreate(),
                ["GamePage"]        = GamePage(),
                ["NamedItem"]       = NamedItem(),
                ["NamedItemCreate"] = NamedItemCreate(),
                ["Platform"]        = Platform(),
            };
        }

        // ─── individual schemas ──────────────────────────────────────────

        private static JObject Error() => new JObject
        {
            ["type"] = "object",
            ["required"] = new JArray("error", "message"),
            ["properties"] = new JObject
            {
                ["error"]   = StringProp("Short error code (e.g. \"not_found\", \"writes_disabled\")"),
                ["message"] = StringProp("Human-readable description"),
            },
        };

        // Fields whose schema is hand-rendered by the explicit overrides at
        // the bottom of Game() instead of going through ShapeToJson. Adding
        // a key here means you must also add a corresponding override line.
        // Today: only releaseDate, because Playnite's ReleaseDate is a
        // nested struct (year, month, day) rather than a scalar.
        private static readonly HashSet<string> ExplicitOverrides =
            new HashSet<string>(System.StringComparer.OrdinalIgnoreCase) { "releaseDate" };

        private static JObject Game()
        {
            var properties = new JObject();

            // Read-only header — server-managed identity. These appear in
            // responses but are not in AllowedPatchFields.
            properties["id"] = StringProp("Server-assigned uuid", format: "uuid");

            // Walk the patch allow-list, skipping any key that has an
            // explicit hand-rendered override below. The Dictionary preserves
            // insertion order (Newtonsoft does too), so the schema field
            // order matches the declaration order in GamesController.
            foreach (var kvp in GamesController.AllowedPatchFields)
            {
                if (ExplicitOverrides.Contains(kvp.Key))
                {
                    continue;
                }
                properties[kvp.Key] = ShapeToJson(kvp.Value);
            }

            // Explicit override: ReleaseDate is a struct, not a string.
            // If you delete this line, releaseDate will be missing from
            // the schema (the loop above skips it).
            properties["releaseDate"] = ReleaseDateSchema();

            return new JObject
            {
                ["type"] = "object",
                ["additionalProperties"] = true,  // SDK exposes more fields than we document
                ["properties"] = properties,
                ["description"] = "A Playnite game. The documented properties cover the writable patch surface plus the server-assigned id; the SDK serializes additional read-only fields that are not enumerated here.",
            };
        }

        private static JObject ReleaseDateSchema() => new JObject
        {
            ["type"] = "object",
            ["nullable"] = true,
            ["description"] = "Playnite's ReleaseDate struct. Pass year/month/day to set; null to clear. Responses also include a computed 'date' (ISO 8601) derived by the SDK; not listed here because the schema's 'additionalProperties: true' on Game already permits it.",
            ["properties"] = new JObject
            {
                ["year"]  = new JObject { ["type"] = "integer", ["description"] = "Four-digit year" },
                ["month"] = new JObject { ["type"] = "integer", ["nullable"] = true, ["description"] = "1–12, optional" },
                ["day"]   = new JObject { ["type"] = "integer", ["nullable"] = true, ["description"] = "1–31, optional" },
            },
            ["required"] = new JArray("year"),
        };

        private static JObject GameCreate() => new JObject
        {
            ["type"] = "object",
            ["required"] = new JArray("name"),
            ["properties"] = new JObject
            {
                ["name"] = StringProp("Display name (required)"),
            },
        };

        private static JObject GamePage() => new JObject
        {
            ["type"] = "object",
            ["required"] = new JArray("total", "offset", "limit", "items"),
            ["properties"] = new JObject
            {
                ["total"]  = new JObject { ["type"] = "integer", ["description"] = "Total games matching the filter" },
                ["offset"] = new JObject { ["type"] = "integer", ["description"] = "Offset used for this page" },
                ["limit"]  = new JObject { ["type"] = "integer", ["description"] = "Page size used (capped at 1000)" },
                ["items"]  = new JObject
                {
                    ["type"] = "array",
                    ["items"] = new JObject { ["$ref"] = Schemas.Game },
                },
            },
        };

        // NamedItem and Platform mirror Game's additionalProperties=true:
        // the Playnite SDK exposes more fields on each lookup type than
        // we hand-author here, and we don't want to surface conformance
        // errors when the SDK adds a new field.
        private static JObject NamedItem() => new JObject
        {
            ["type"] = "object",
            ["additionalProperties"] = true,
            ["required"] = new JArray("id", "name"),
            ["properties"] = new JObject
            {
                ["id"]   = StringProp("Server-assigned uuid", format: "uuid"),
                ["name"] = StringProp("Display name"),
            },
        };

        private static JObject NamedItemCreate() => new JObject
        {
            ["type"] = "object",
            ["required"] = new JArray("name"),
            ["properties"] = new JObject
            {
                ["name"] = StringProp("Display name (required)"),
            },
        };

        private static JObject Platform() => new JObject
        {
            ["type"] = "object",
            ["additionalProperties"] = true,
            ["required"] = new JArray("id", "name"),
            ["properties"] = new JObject
            {
                ["id"]              = StringProp("Server-assigned uuid", format: "uuid"),
                ["name"]            = StringProp("Display name"),
                ["specificationId"] = StringProp("Optional Playnite platform spec id (e.g. \"sony_playstation2\")"),
                ["icon"]            = StringProp("Icon path / URL / database id"),
                ["cover"]           = StringProp("Cover image path / URL / database id"),
                ["background"]      = StringProp("Background image path / URL / database id"),
            },
        };

        // ─── helpers ─────────────────────────────────────────────────────

        private static JObject StringProp(string description, string format = null)
        {
            var o = new JObject { ["type"] = "string", ["description"] = description };
            if (format != null)
            {
                o["format"] = format;
            }
            return o;
        }

        private static JObject ShapeToJson(FieldShape shape)
        {
            var o = new JObject { ["type"] = shape.Type };

            if (shape.Format != null)
            {
                o["format"] = shape.Format;
            }
            if (shape.Description != null)
            {
                o["description"] = shape.Description;
            }
            if (shape.Nullable)
            {
                o["nullable"] = true;
            }
            if (shape.Type == "array")
            {
                var items = new JObject { ["type"] = shape.ItemType ?? "string" };
                if (shape.ItemFormat != null)
                {
                    items["format"] = shape.ItemFormat;
                }
                o["items"] = items;
            }
            if (shape.EnumValues != null && shape.EnumValues.Count > 0)
            {
                o["enum"] = new JArray(shape.EnumValues);
            }
            return o;
        }
    }
}
